name: hola-mundo
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Public ip
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Hola mundo
        run: echo hola mundo desde ${{steps.ip.outputs.ipv4}}
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          node-version: 18
      - name: Run index
        run: node index.js

